### ISSUE TITLE
SOLID: Create parameterized SolidLogin() to replace podnotes/login/screen.dart

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#1]
# Description

Our current login screen is common across the gurriny apps and podnotes. 

This task will add SolidLogin() to the SOLID package to implement this generic widget.

# Milestones

Treat each milestone here as a **new issue and branch and create a PR for each** as we proceed. Each PR should be reviewed by two others before agreeing to merge the PR. Feel free to split into separate issues if that works better for you (I ran out of time).

Milestones:

- [x] 1: Solid connection from keypod
- [x] 2: Dummy SolidLogin https://github.com/anusii/solid/issues/7 - done @gjwgit.
- [x] 3: Basic Widget with Authentication https://github.com/anusii/solid/issues/11
- [ ] 4: POD Initialisation. See #2 Add the initialise functionality when the folder named as the `folder: ` parameter is not present on the user's POD. Initialise the folder with a simple two entry key-value pair file containing: `<user,license,123456>, <user,health,54321>`, as well as the master key and other required files, but not password or personal information. For now, the file is not encrypted.
- [ ] Replace the MyHomePage() widget with a simple text view widget to display the current contents of the key-value pairs file.
- [ ] Replace the simple text view widget with a widget to edit/add the key-value pairs to the saved file.
- [ ] Add encryption option as a parameter to the `SolidLogin(encrypted: True)` when true will prompt for the password in the initialise files.
- [ ] Add reading/writing the files encrypted.

It will utilise code from podnotes/login/screen.dart, abstract it out to solid/login.dart as a Widget SolidLogin, with the required parameters that might **eventually** include:

- mainImage: The photo (often) used as the main display on the login screen with a default being `indipod/assets/images/anu_aerial_view_square.jpg`
- topLogo: the image file to display in the login window
- button colours: default colours as in PODNOTES but can be changed as in INDI app
- showVersion: a Boolean to show the version umber as in the INDI app
- showSolidProject: a Boolean to include a Visit solidproject link as in the INDI app
- defaultWebID: default is https://pods.solidcommunity.au as in PODNOTES but overriden as in INDI app
-  title: "LOGIN WITH YOUR POD" by default but can be changed as in INDI app.
- mainScreen: the widget to pass on to after authenticated

![Image](https://github.com/anusii/solid-core/assets/1681429/5f9910ab-370e-4963-a1a5-642286efcc83)

![Image](https://github.com/anusii/solid-core/assets/1681429/742f685b-6623-41be-8318-f683e3a45bd8)

**Comment by gjwgit** [comment]
Current status: Milestone 3 is under review.

**Comment by gjwgit** [comment]
Close this issue now since I've created other NEW issues.
