### ISSUE TITLE
WRITEPOD: Implement writePod() to push Solid Pod datafile from app

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#78]
## Depends

- [x] https://github.com/anusii/solidpod/issues/77

## Description

A Solid Pod app will want to write (encrypted) datafiles (ttl) to the `data` folder on the Pod. We also want to hide any complexity from the app developer.

This task is to implement writePod() in `solidpod` and demonstrate it's use in `keypod`.

- [x] Check style guidelines - is this `writePod()` or `WritePod()`.

writePod() needs the following parameters:

**TODO**
- [x] Get master password from local secure storage, otherwise ask user to provide the master password
- [x] Verify master password using the verification key stored in PODs
- [x] Use a popup window for user to provide the master password if verification failed
- [x] Encrypt data and format encrypted data in TTL format (if data file already exists, reuse its individual key and IV) 
- [x]  Save encrypted data to PODs (delete the file first if it already exists)
- [x] Update `ind-key.ttl` with the individual key and IV for the encrypted data (if applicable)
- [x] Add an editable table for user to input key/value pairs in [keypod](https://github.com/anusii/keypod) and write data in TTL format (e.g. using [rdflib](https://github.com/anusii/rdflib/))

## Why

So that a Solid Pod based app developer can very simply push data to the pod.

## Closing Criteria

- [x] KeyPod demonstrates the use of writePod() by saving a sample text to a file in the pod, then retrieving it to then display and confirm.

**Comment by cdawei** [comment]
A keypod demo showing:
- Write one key-value pair to POD
- Read that key-value pair from POD and display
- Add one more key-value pair and then write to POD

https://github.com/anusii/solidpod/assets/13044715/7e2d0b68-9019-485c-93d1-dd9dfd67c2bb
